### ISSUE TITLE
can't modify frozen Hash:

### ISSUE THREAD

**Issue by ohpreis** [kiskolabs/humanizer#54]
After upgrading to Rails 7 and Ruby 3.0.3 I get the following error. 
`can't modify frozen Hash: {:question=>"Two plus two?", :answers=>["4", "four"]}`

Did anyone else have this issue, and if yes, how did you fix it. 

Any help is appreciated. 

Thanks

**Comment by vesan** [comment]
We have not bumped into this. Can you paste a longer stacktrace? Which line raises that error?

**Comment by ohpreis** [comment]
@vesan - Sorry for that long delay. 

Here is a longer stack trace. 
I hope what I provided will help, and thank you for looking into that. 

~~~
humanizer (2.6.4) lib/humanizer.rb:35:in `default_proc=
humanizer (2.6.4) lib/humanizer.rb:35:in `block in humanizer_questions'
humanizer (2.6.4) lib/humanizer.rb:34:in `map'
humanizer (2.6.4) lib/humanizer.rb:34:in `humanizer_questions'
humanizer (2.6.4) lib/humanizer.rb:11:in `humanizer_question'
app/views/feedbacks/_form.html.erb:50
actionview (7.0.2.2) lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
actionview (7.0.2.2) lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
actionview (7.0.2.2) lib/action_view/helpers/capture_helper.rb:45:in `capture'
actionview (7.0.2.2) lib/action_view/helpers/form_helper.rb:768:in `form_with'
app/views/feedbacks/_form.html.erb:1
actionview (7.0.2.2) lib/action_view/base.rb:244:in `public_send'
actionview (7.0.2.2) lib/action_view/base.rb:244:in `_run'
actionview (7.0.2.2) lib/action_view/template.rb:157:in `block in render'
activesupport (7.0.2.2) lib/active_support/notifications.rb:208:in `instrument'
actionview (7.0.2.2) lib/action_view/template.rb:361:in `instrument_render_template'
actionview (7.0.2.2) lib/action_view/template.rb:155:in `render'
actionview (7.0.2.2) lib/action_view/renderer/partial_renderer.rb:251:in `block in render_partial_template'
activesupport (7.0.2.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.2.2) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.2.2) lib/action_view/renderer/partial_renderer.rb:246:in `render_partial_template'
actionview (7.0.2.2) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionview (7.0.2.2) lib/action_view/renderer/renderer.rb:81:in `render_partial_to_object'
actionview (7.0.2.2) lib/action_view/renderer/renderer.rb:53:in `render_partial'
actionview (7.0.2.2) lib/action_view/helpers/rendering_helper.rb:45:in `render'
app/views/home/contact.html.erb:36
actionview (7.0.2.2) lib/action_view/base.rb:244:in `public_send'
actionview (7.0.2.2) lib/action_view/base.rb:244:in `_run'
actionview (7.0.2.2) lib/action_view/template.rb:157:in `block in render'
activesupport (7.0.2.2) lib/active_support/notifications.rb:208:in `instrument'
actionview (7.0.2.2) lib/action_view/template.rb:361:in `instrument_render_template'
actionview (7.0.2.2) lib/action_view/template.rb:155:in `render'
actionview (7.0.2.2) lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
activesupport (7.0.2.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.2.2) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.2.2) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
actionview (7.0.2.2) lib/action_view/renderer/template_renderer.rb:75:in `block in render_with_layout'
activesupport (7.0.2.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.2.2) lib/active_support/notifications.rb:206:in `instrument'
actionview (7.0.2.2) lib/action_view/renderer/template_renderer.rb:74:in `render_with_layout'
actionview (7.0.2.2) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
actionview (7.0.2.2) lib/action_view/renderer/template_renderer.rb:11:in `render'
actionview (7.0.2.2) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
actionview (7.0.2.2) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
actionview (7.0.2.2) lib/action_view/rendering.rb:117:in `block in _render_template'
actionview (7.0.2.2) lib/action_view/base.rb:270:in `in_rendering_context'
actionview (7.0.2.2) lib/action_view/rendering.rb:116:in `_render_template'
actionpack (7.0.2.2) lib/action_controller/metal/streaming.rb:216:in `_render_template'
actionview (7.0.2.2) lib/action_view/rendering.rb:103:in `render_to_body'
actionpack (7.0.2.2) lib/action_controller/metal/rendering.rb:46:in `render_to_body'
actionpack (7.0.2.2) lib/action_controller/metal/renderers.rb:142:in `render_to_body'
actionpack (7.0.2.2) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (7.0.2.2) lib/action_controller/metal/rendering.rb:30:in `render'
actionpack (7.0.2.2) lib/action_controller/metal/instrumentation.rb:22:in `block (2 levels) in render'
C:/Ruby30-x64/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
activesupport (7.0.2.2) lib/active_support/core_ext/benchmark.rb:14:in `ms'
actionpack (7.0.2.2) lib/action_controller/metal/instrumentation.rb:22:in `block in render'
actionpack (7.0.2.2) lib/action_controller/metal/instrumentation.rb:91:in `cleanup_view_runtime'
activerecord (7.0.2.2) lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
actionpack (7.0.2.2) lib/action_controller/metal/instrumentation.rb:21:in `render'
actionpack (7.0.2.2) lib/action_controller/metal/implicit_render.rb:35:in `default_render'
actionpack (7.0.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
<internal:kernel>:90:in `tap'
actionpack (7.0.2.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (7.0.2.2) lib/abstract_controller/base.rb:214:in `process_action'
actionpack (7.0.2.2) lib/action_controller/metal/rendering.rb:53:in `process_action'
actionpack (7.0.2.2) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
activesupport (7.0.2.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
actiontext (7.0.2.2) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (7.0.2.2) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.0.2.2) lib/active_support/callbacks.rb:127:in `instance_exec'
activesupport (7.0.2.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
activesupport (7.0.2.2) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.2.2) lib/abstract_controller/callbacks.rb:233:in `process_action'
actionpack (7.0.2.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (7.0.2.2) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
activesupport (7.0.2.2) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.2.2) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.0.2.2) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
actionpack (7.0.2.2) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
activerecord (7.0.2.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (7.0.2.2) lib/abstract_controller/base.rb:151:in `process'
actionview (7.0.2.2) lib/action_view/rendering.rb:39:in `process'
actionpack (7.0.2.2) lib/action_controller/metal.rb:188:in `dispatch'
actionpack (7.0.2.2) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.2.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.2.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.2.2) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.2.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.2.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.2.2) lib/action_dispatch/routing/route_set.rb:850:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (7.0.2.2) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (7.0.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.2.2) lib/action_dispatch/middleware/cookies.rb:693:in `call'
activerecord (7.0.2.2) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.2.2) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.2.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (7.0.2.2) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.2.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (7.0.2.2) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.2.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.2.2) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.2.2) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.2.2) lib/rails/rack/logger.rb:25:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.2.2) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.2.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.2.2) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.2.2) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
railties (7.0.2.2) lib/rails/engine.rb:530:in `call'
puma (5.6.2) lib/puma/configuration.rb:252:in `call'
puma (5.6.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.2) lib/puma/request.rb:76:in `handle_request'
puma (5.6.2) lib/puma/server.rb:441:in `process_client'
puma (5.6.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread' `
~~~
And here is the form element that uses humanizer
~~~
    <div class="col-md-12">
      <div class="mb-3">
        <%= form.label :humanizer_answer, @feedback.humanizer_question, class: "form-label" %>
        <%= form.text_field :humanizer_answer, class: "form-control" %>
        <%= form.hidden_field :humanizer_question_id %>
      </div>
~~~

Hope this helps, and thank you for looking into that. 

Oscar

**Comment by unRARed** [comment]
Also running into this on our app today:

```
    # --- Caused by: ---
     # FrozenError:
     #   can't modify frozen Hash: {:question=>"Two plus two?", :answers=>["4", "four"]}
     #   /Users/ryanrichardson/.rvm/gems/ruby-2.7.5@starwatch/gems/humanizer-2.6.4/lib/humanizer.rb:35:in `default_proc='
```
